# Generated by Django 4.2.7 on 2026-03-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('total_emails', models.IntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
